name: Auto Update README from Issues

on:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Generate README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/generate_readme.py

      - name: Commit & Push if changed
        run: |
          if git diff --quiet; then
            echo "No changes"
          else
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add README.md
            git commit -m "chore: auto update README from issues"
            git push
          fi
